services:
  - type: web
    name: wxbrief
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: RAPIDAPI_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0